### ISSUE TITLE
String concatenation on paramter to OPENUP not expanded

### ISSUE THREAD

**Issue by soruk42** [stardot/MatrixBrandy#1]
When opening a file or network stream, for example `H%=OPENUP "ip4:"+H$`
this is not handled correctly, and the code block is passed ip4:"+H$ - which obviously doesn't work, additionally, th

Current workarounds are to either build the string then pass the completed string as OPENUP H$ works, alternatively H%=OPENUP("ip4:"+H$) works too.

**Comment by soruk42** [comment]
Closing this, while the passing of the part of the string seems wrong, the additioin is behaving the same as on RISC OS BBC BASIC - so the parentheses are required when concatenating strings for the filename.

**Comment by jgharston** [comment]
To confirm, functions are the ***HIGHEST*** priority in the evaluator just below brackets.
num=OPENIN A$+B$ is OPENIN A$ then +B$. What would you expect num=(OPENIN A$)+(B$) to do?
Exactly the same as A$=CHR$ A%+B%, exactly the same as A%=LEN A$+B$, exactly the same as A%=ABS B%+C%, exactly the same as A=COS B+C.
