### ISSUE TITLE
Not really an issue.  Windows Build?

### ISSUE THREAD

**Issue by mva1985** [stardot/MatrixBrandy#11]
any chance of getting a windows build for this?

**Comment by soruk42** [comment]
I've got a new Makefile for building with MinGW and SDL under Cygwin, the resulting binary is not dependent on Cygwin.
Gotchas:
1) Networking doesn't work - and I know nothing about the Windows network stack
2) It's hardly tested.....

**Comment by mva1985** [comment]
I'd be happy to give it a test on my laptop if you'd like?

**Comment by soruk42** [comment]
Here's a test build - http://brandy.matrixnetwork.co.uk/testing/brandy-1.21.12.zip - it's built on my 32-bit netbook. It appears to run OK on 64-bit Windows.

**Comment by mva1985** [comment]
thanks so much...  i'll give it a shot

**Comment by mva1985** [comment]
Did some playing around with the demo programs and did not encounter any problems on my Windows 7 laptop.

And it is fast!!

LISTO options are kinda confusing but I did figure it out.  Would be kinda nice if they could be made permanent somehow to last from session to session

**Comment by soruk42** [comment]
While Windows isn't a primary focus of my work on Matrix Brandy, I have linked, and will continue to link, a download to the Windows executable from the main website at http://brandy.matrixnetwork.co.uk/

Some issues remain, for example * commands that produce output by calling a shell command (e.g. *dir under Windows and *ls under Linux) don't get any output.

**Comment by soruk42** [comment]
Just a heads-up - V1.21.14 is out, and I've also uploaded a Windows build on the website. This is something I will continue to do (indeed I've graduated from the netbook and installed Cygwin on a Win7(x86) VM on my server which I can SSH into!)

If you want to try building from source yourself, use Cygwin, but you need the MinGW gcc compiler, MinGW version of the SDL 1.2.15 library. Normal make and binutils will work fine, and you'll also want to install git to follow the repository. Then, once downloaded, you'll need to build using
`make -f makefile.mingw-sdl`. The resulting binary (brandy.exe) will not require any Cygwin component to be present on the target system, and will run happily as a standalone EXE.

**Comment by soruk42** [comment]
Closing this, as we now have Windows builds and a pretty easy way of building binaries.
