### ISSUE TITLE
Add Sound capability

### ISSUE THREAD

**Issue by soruk42** [stardot/MatrixBrandy#12]
Sound is a glaring part of BBC BASIC that is currently missing from Brandy.

I've taken an initial look at the audio from BeebEm (which also uses SDL 1.2) but it is extremely tightly tied to the emulated sound hardware of the Beeb.

**Comment by jgharston** [comment]
Non-envelope sound might be easily do-able. Certainly, SOUND to MIDI is quite simple.

**Comment by soruk42** [comment]
Earlier today I received a code submission by email that provides sound and (nominally) the default RISC OS sounds. Wavesynth-Beep gives a softer sound, StringLib-* give what sound like a square wave, and Percussion-* play distorted notes.
