### ISSUE TITLE
Quotes in DATA parsed incorrectly

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#14]
10 READ A$:PRINT A$
20 DATA "'/"""
should set A$ to the 3-character string '/" 
it incorrectly sets A$ to the 1-character string '
Quotes in DATA strings should be parsed as in any other constant string, eg A$="->""<-" correctly sets A$ to the string ->"<-

**Comment by soruk42** [comment]
OK, that's odd. I'm getting the two-character string '/ - which, admittedly, is still wrong.

**Comment by soruk42** [comment]
This is currently on the "iss14-data-parse-error" branch. Please let me know if it works for you - it works on both 32-bit and 64-bit for me, under Linux.
