### ISSUE TITLE
MODE 7: Flash seems not to be working.

### ISSUE THREAD

**Issue by WiggyWire** [stardot/MatrixBrandy#16]
When trying to run the following code flash does not seem to be rendered in Mode 7.

`10 MODE 7

20 PRINT CHR$(141);CHR$(157);CHR$(129);

CHR$(136); "THE LOT"

30 PRINT CHR$(141);CHR$(157);CHR$(129);

CHR$(136); "THE LOT"`

**Comment by soruk42** [comment]
I can't reproduce this, it is working for me.

Please can you give me specifics on your setup?

**Comment by WiggyWire** [comment]
Sure, I am using 1.21.16, I compiled it on a version of Debian linux.

**Comment by soruk42** [comment]
32-bit or 64-bit? And, from  the release tarball or latest from Git tree?

**Comment by WiggyWire** [comment]
Its 64 bit, I cloned the project from Git yesterday.

**Comment by soruk42** [comment]
OK, interesting. I can reproduce it on my 64-bit box, but not 32-bit.

**Comment by soruk42** [comment]
OK. Should be fixed. Please update your git tree and rebuild.

**Comment by WiggyWire** [comment]
It works now thanks very much! Great program by the way.
