### ISSUE TITLE
Non-function special keys not modified

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#19]
Non-function special keys are not modified by modifier keys.
Shift/Ctrl/Alt plus arrows,Ins,PgUp,PgDn,End should EOR 0x10 or 0x20 with the keypress.
For example:
PgUp=&9F, Shift+PgUp=&8F
Up=&8F, Shift+Up=&9F
See http://mdfs.net/Docs/Comp/KeyMap/RISCOS

keyboard.c is a big mess, when I was working on the Napoleon fork four years ago I was about to print the whole lot out and edit it with scissors and tape. When the negative INKEYs is done, I'll have a look at tidying the whole lot up.

**Comment by jgharston** [comment]
I've pushed an update that deals with non-function special keys correctly.
Also correctly detects DELETE.
Windows MinGW/SDL build tested locally.

**Comment by soruk42** [comment]
These have been picked up in recent merges (and hopefully in time for the V1.21.17 release!)
