### ISSUE TITLE
Recommend filename rationalisation

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#22]
Recommend renaming:
keyboard-inkey.h to inkey.h
mos_swinums.h    to swinums.h
mos_sys.c             to swis.c

Gets rid of unncessessarily-long and unneccessary hyphenated names, gets rid of inconsitant hyphen/underline-ation, makes names more consitant with contents, eg, when looking for SWI handling I look for s... not m... Also, closer match to RISC OS source naming. ;)

**Comment by jgharston** [comment]
Also, trying to get the RISC OS build working reminds that having filenames in src longer than 10 characters makes it really fiddly.

**Comment by soruk42** [comment]
keyboard-inkey.h has been renamed to inkey.h in a recent update.

**Comment by soruk42** [comment]
I don't want to rename mos_sys.c to swis.c - the current name isn't too long, and it shows that the SYS functionality is OS-level rather than BASIC.

**Comment by soruk42** [comment]
mos_swinums.h renamed to mos_sys.h

This now makes all the names short enough.
