### ISSUE TITLE
MODE &87 doesn't select MODE 7

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#29]
MODE &87 doesn't select MODE 7, it is treated as an unknown MODE and selects MODE 0. All other shadow MODEs are correctly selected. The flaw is in 
graphsdl.c -> setup_mode() where:
  modecopy = mode;
  mode = mode & MODEMASK;	/* Lose 'shadow mode' bit */

needs to be before the first paragraph.
(Can't do an upload from here otherwise I'd fix it.)

**Comment by soruk42** [comment]
Fixed. Merry Christmas!
