### ISSUE TITLE
USE_ANSI build broken

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#30]
Building with USE_ANSI defined should instruct the VDU driver to use ANSI control codes (eg esc[...m for colours), but building throws loads of errors. A USE_ANSI build has probably not been tested for some time and modifications for other targets have broken it.

**Comment by soruk42** [comment]
From the UNIX point of view, the text-mode built binary "tbrandy" it uses ANSI codes regardless the USE_ANSI setting, I guess "conio" as mentioned in the header comments refers to the DOS mode build?

**Comment by soruk42** [comment]
As it happens, unless you're building on a small handful of targets, text-mode builds explicity define USE_ANSI in line 48 - which is why the Linux textmode build is using ANSI - and there are no build errors.

**Comment by jgharston** [comment]
I'm getting errors trying to do a build with ANSI keyboard codes, but several hours down rabbit holes has revealed pointers to where the build is going wrong, so it's in my list of code to address in addressing the keyboard code when I've got the current legacy code finished off.

**Comment by jgharston** [comment]
ANSI keypress code rewritten. Build tested and working on CentOS.
