### ISSUE TITLE
VDU 20 not working

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#36]
COLOUR 129:COLOUR 3:PRINT "Hello":VDU 20:PRINT "there"
should print 'there' in colour 7 on colour 128 (white on black), but actually prints in the same as 'Hello'.

**Comment by soruk42** [comment]
Unable to replicate.
![iss36](https://user-images.githubusercontent.com/41840902/50564955-d202ee00-0d21-11e9-946c-78ed88bed904.png)

**Comment by jgharston** [comment]
On 31-12-2018 17:31, Michael McConnell wrote:
> Unable to replicate.

I'll do a fresh download of the master and rebuild and see if it
still comes up.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
I did find a problem with this in the text-mode build in textmode.c - I've pushed a fix.
