### ISSUE TITLE
Sync problems

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#42]
I've just tried to update my fork with the latest code, but am getting:
 Can’t automatically merge. Don’t worry, you can still create the pull request.

but without any actual option to continue to create the pull request :(

**Comment by soruk42** [comment]
OK, that has me stumped.

If my tree has everything you've done, perhaps the safest is to nuke your tree and re-fork from mine?

**Comment by jgharston** [comment]
Michael McConnell wrote:
> OK, that has me stumped.
> 
> If my tree has everything you've done, perhaps the safest is to nuke
> your tree and re-fork from mine?

That's what I've been thinking of doing.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by jgharston** [comment]
I've found a different method, which solves this problem. Will close the issue.
