### ISSUE TITLE
RISC OS build broken (v1.22.0)

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#48]
I was fighting with this all yesterday get get a stable base before starting work on the keyboard code.
The current RISC OS build bombs out on startup.
See http://mdfs.net/Software/BBCBasic/Brandy/matrix/img/ for screenshots.

With a Wimp slot of 1200K from v21/18, it dies with an EMT error. On investigating, FAQs state this is due to there not being enough stack space on startup, so WimpSpace needs to be increased. However, doing that just results in a machine crash. I've tried upping WimpSlot to 12,000K and it still fails.
Version 1.21.18, 28 Dec 2018 works fine.
I've trawlled through the current code, have experimentally commented bits out and back again, and can't find what change has caused this. Unless anybody else can find the problem, my next step is to go back to v1.21.18 and incrementally add stuff back in until it falls over.

**Comment by soruk42** [comment]
Could it be that I'm now using a multithreaded approach for the timer, rather than the timer slowing Brandy down in the primary thread? Might need to #ifndef RISCOS that bit.

**Comment by soruk42** [comment]
Closing this as my build tree now compiles in RISC OS both 26-bit and 32-bit. Build scripts aren't (yet) in git, however, as not yet sure how I'm going to preserve RISC OS file types in git. Might use what HostFS uses under the lid.
