### ISSUE TITLE
PAGE has unexpected value

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#53]
With the current build PAGE now unexpectedly returns &8F00. That causes all sorts of problems with programs that see PAGE=&8F00 as meaning the program is running on ARM BASIC (as distinct from running on RISC OS which is the OSBYTE 0 value).

If CALL &FFxx/USR &FFxx access a BBC filing system entry block, then PAGE needs to be <&FFFF so that common code that does, eg:
IF PAGE<&FFFF THEN CALL &FFDD ELSE do something else

As currently the only &FFxx entry point implemented is a subset of OSBYTE/OSWORD, PAGE should return a value >&FFFF. Probably larger than &1FFFF as Basic128 has PAGE=&10000.

**Comment by soruk42** [comment]
I'm not sure I entirely follow the reasoning here.

However, PAGE on ARM BASIC VI is even higher, at &9700 - and doesn't support the BBC entry points at all.
![fff4](https://user-images.githubusercontent.com/41840902/63746785-80553800-c89d-11e9-9fb1-01927a612b78.png)

**Comment by jgharston** [comment]
On 27-08-2019 07:37, Michael McConnell wrote:
> I'm not sure I entirely follow the reasoning here.

While things like OSBYTE 0 and INKEY-256 will tell a program what host 
hardware and operating system it is running on, that doesn't tell the 
running program what *interpreter* it is running on. There is no defined 
way to determine this, and various workarounds have been worked up over 
the decades, which have to rely on what the running program can 
determine of *BASIC*'s environment, not the host's environment.

Assuming a running program doesn't change them itself, PAGE, TOP, LOMEM 
and HIMEM describe the BASIC program's environment. (In the case where 
the running program wants to change them, then any tests would be done 
*before* the change).

The simplest first:
If you're running in a 64K memory, then HIMEM can't be greater than 
&FFFF; if you're running with more than 64K then HIMEM is going to be 
greater than &FFFF. So, a simple test:

IF HIMEM < &FFFF then small amount of memory
IF HIMEM > &FFFF then large amount of memory

This is useful for programs that may need to adapt their behaviour when 
memory is tight, but can be looser when there's plenty of memory. For 
example, ARM BASIC puts program stacks on the BASIC stack, but 6502 
BASIC has dedicates REPEAT/FOR/GOSUB stacks. So, if you use the samme 
HIMEM-LOMEM-something formula to claim memory ARM BASIC runs out of 
memory as it needs more stack space. So, if HIMEM>&FFFF claim less 
memory, which isn't so onerous as you've got tons of memory anyway. 
Typically something like:
max%=HIMEM-LOMEM-2048*(2+(HIMEM<&FFFF)):DIM mem max%

(Bas128 actually has PAGE=&10000 and HIMEM=&20000, so that treats 
exactly 64K of memory as being a large amount of memory.)


Looking at the other end, when running in a 64K memory, PAGE can't be 
greater than &FFFF (see note). All BASICs that run in a 64K memory in a 
BBC API environment have access to the BBC API via calling &FFxx. Those 
BASICs that have PAGE above the 64K mark don't translate CALL &FFxx to 
the BBC API (or have a very restricted implementation).

Additionally, those BASIC that operate in more than 64K, but do 
translate calls to &FFxx to the BBC API also do have PAGE<&FFFF - ARM 
BASIC and 32000 BASIC.

Consequently, the test PAGE<&FFFF is a useful test for the ability to do 
CALL &FFxx to access the BBC API. Classically, Brandy has had PAGE=0, so 
a slight modification is used to:

IF PAGE:IF PAGE<&FFFF: etc.

This has allowed code for many years to do things like:

IF PAGE:IF PAGE<&FFFF:A%=0:Y%=0:E%=0:filingsystem%=(USR&FFDA)AND&FF ELSE 
some default

IF PAGE:IF PAGE<&FFFF:CALL OSGBPB ELSE copy data manually

IF PAGE:IF PAGE<&FFFF:A%=5:object%=(USR OSFILE)AND&FF ELSE do something 
else


Additionally, various ranges of PAGE are used to get past the 
problematic issue of finding various startup settings. PAGE=&8F00 is 
more-or-less *stating* that the program is running on ARM BASIC V, and 
that the string buffer is at &8100 and the error buffer is at &8000, 
similarly with BASIC VI with PAGE at &9-something and ARM Development 
BASIC with PAGE at &C-something. Things like the tokeniser library and 
the ProgEnv library have no other way to find this info.

Having PAGE=&8F00 and *not* running on ARM BASIC is the environment 
lying to the programmer. Having PAGE<&FFFF and *not* being able to 
access the Acorn FileSwitch entries at &FFxx is lying to the programmer. 
There are already a lot of hoops to jump through for programs that want 
to be able to run on multiple platforms, adding more hoops to jump 
through that would requires dozens, hundreds, thousands, of existing 
programs to be amended, adds unnessary complexity for zero gain.

This can't be done by testing OSBYTE 0 or INKEY-256, because that 
doesn't tell you *the* *BASIC*, it tells you *the* *host* *operating* 
*system*.

os%=2 could be 6502 BASIC, could be Z80 BASIC running on a CoPro, could 
be PDP11 Basic running on a CoPro, could be ARM Basic running on a 
CoPro, could be 32000 Basic running on a CoPro, could be Brandy Basic 
running on a CoPro.

os%=8, again, could be 6502/Z80/PDP11/ARM/Brandy running on a Unix 
system.

os%=32 could be 6502/Z80/PDP11/ARM Basic running on a 6502 CoPro 
hardware or emulator on Windows or could be Brandy running on Windows.

INKEY-256=&FE could be Brandy running on Linux, or could be Z80 Basic 
running on Linux, or could be PDP11 Basic running on Linux, or could be 
a BBC B+ with American MOS. If I finish writing the emulator, it could 
be 6502 Basic running on Linux.

In Brandy's specific example, the program memory addresses really should 
be the plain unadorned absolute addresses that the interpreter "sees" 
internally, If malloc() gives Brandy a block of memory starting at, eg, 
&1280400 to store the Basic program, then PAGE should be &1280400.


Addressing the issue of ARM BASIC VI not having the CALL &FFxx entries, 
if you are writing code to work on multiple platforms, you wouldn't be 
targetting ARM BASIC VI anyway, you'd be targetting ARM BASIC V. Code 
that specifically wants to be using ARM BASIC VI would specifically run 
with ARM BASIC VI and by targetting ARM BASIC VI it wouldn't be code 
being written to work on multiple platforms.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
> Consequently, the test PAGE<&FFFF is a useful test for the ability to do CALL &FFxx to access the BBC API.
...
Having PAGE<&FFFF and *not* being able to access the Acorn FileSwitch entries at &FFxx is lying to the programmer.

This doesn't hold true for ARM BASIC VI - PAGE is &9700 but CALL to &FFxx doesn't work:
![basic6](https://user-images.githubusercontent.com/41840902/64151275-e99af500-ce21-11e9-9f0a-e5ab1a209a6f.png)

I could raise PAGE to &9700, as most &FFxx are not implemented in Brandy, and none at all are supported in ARM BASIC VI. Or, we just choose a new value. (If memory size is <= 64K Matrix Brandy sets page to &E00, and additionally if <= 31K then MODE 7 video space is at &7C00. There is a SYS call to determine the actual location of MODE 7 space.)

I agree with your point about PAGE etc should be the actual location in RAM, but until I've got the 64-bit integers fully working it would stop Brandy working properly (if not at all) on 64-bit systems. So, for now the mechanism of using an offset from workspace memory will have to stay.

**Comment by soruk42** [comment]
Closing this as PAGE is no longer an offset but the actual value in RAM.
