### ISSUE TITLE
INKEY-256 returns wrong info

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#72]
"X=&4D Matrix Brandy BASIC (ie ASC"M") for all builds from V1.22.6 except RISC OS."

Wrong. INKEY-256 must return the *platform*, *NOT* the interpeter. It's a call to the *HOST*, *NOT* the interpreter. It's "Check machine type" not "Check interpreter type". Doing this builds in another IF this THEN dothis ELSE an exception ELSE another excpetion ELSE another exception. There are pre-existing methods of determining what functionality the interpreter has (http://beebwiki.mdfs.net/What_BASIC_is_running), they must be used, not abusing the "what is the *OPERATING SYSTEM* call, and it breaks the principal of "test for functionality not for psychic ability". It must return the values originally in the target.h file, these ones and similar:
              X=&FB Beos (Brandy Basic)
              X=&FA DOS with DJGPP extender (Brandy Basic)
              X=&F9 Linux
              X=&F8 MacOS X (Brandy Basic)
              X=&F7 FreeBSD
              X=&F6 OpenBSD
              X=&F5 Amiga (Brandy Basic)
              X=&F4 GNU FreeBSD (Brandy Basic)
              X=&F3 GNU (Brandy Basic)

**Comment by jgharston** [comment]
You've killed off the ability to say
"this is a Unixy-platform that is MacOS"
"this is a Unixy-platform that is an Amiga"
"this is a Unixy-platform that is running Linux"
"this is a DOS/Windowy platform that is using DJGPP"
"this is a DOS/Windowy platform that is using MinGW"
That is the functionality of INKEY-256, it must not be broken.

**Comment by soruk42** [comment]
1) The methods you link to require an assembler, thus that check will not be able to run.
2) There is precedent that BBCSDL returns ASC("S") on all builds for Intel regardless of OS, and BB4W returns ASC("W") not &FC.
3) The call SYS "Brandy_Platform" offers detailed information about the host, including the old platform identifier previously returned by INKEY(-256).

I have been searching for a long time for a way for a program to be able to uniquely identify Matrix Brandy without breaking on any other platform.

If you know a way to do it that will not break on any other platform and can restore the old INKEY(-256) values, and that do not require an assembler, then I am open to suggestions, but at this point without this INKEY(-256) change I cannot see it.

**Comment by soruk42** [comment]
The following gets the information you say is killed off:

```
hwtype%=INKEY(-256)`
matrix%=FALSE: IF hwtype% = &4D THEN matrix%=TRUE: SYS"Brandy_Platform" TO ,,,,,hwtype%: REM get legacy INKEY-256 value
```

**Comment by rtrussell** [comment]
> INKEY-256 must return the platform, NOT the interpeter. It's a call to the HOST, NOT the interpreter.

In all 'modern' BBC BASICs (whether an emulator like BeebEm or a native implementation like Matrix Brandy) there isn't a meaningful distinction between 'interpreter' and 'host' because both are part of the same package.  Compatibility considerations mean that 'host' features like OSBYTE and OSWORD must be emulated.

> You've killed off ...

Nothing has been "killed off".  Once you've established what interpreter it is, you can use dialect-specific or implementation-specific code to establish all these things, typically in much more detail than INKEY(-256) could possibly provide.
