### ISSUE TITLE
Problem with "for a% = 1 to 10 step s", where s is a float variable

### ISSUE THREAD

**Issue by mikefairbank** [stardot/MatrixBrandy#81]
I'm trying to run some of my old Archimedes BASIC IV code under Brandy.  Most work great - thank you!  However this bug came up:

Example code:

   10step=5
   20FOR ang%=0 TO 359 STEP step
   30PRINT ang%
   40NEXT
RUN
Error: "Type Mismatch.  Number wanted at line 20".

If I run this under RPCEmu I get the numbers printed out 0, 5, ..., 355.

**Comment by soruk42** [comment]
This commit fixes that issue.
