### ISSUE TITLE
Array matrix-vector multiplication not implemented

### ISSUE THREAD

**Issue by mikefairbank** [stardot/MatrixBrandy#82]
The following code works under RPCEmu but not under Brandy:
   10num_rows%=6
   20DIM vec(2)
   30DIM matrix(num_rows%,2)
   40DIM result(num_rows%)
   50result()=matrix().vec()

On brandy it produces an error message "Type Mismatch.  Arrays must have the same dimension at line 50".  If I change the shape of vec and result to (2,1) and (num_rows,1) respectively, so that the "dot" operation applies to "matrix dot matrix" then it works.  But it seems BBC Basic V/VI could also understand how to do "matrix dot vector".

I've checked the above code under RPCEmu and it produces no error.

**Comment by soruk42** [comment]
This is most likely because I don't actually know the rules of the matrix dot vector - it has been 30 years since I looked at this for GCSE maths!

**Comment by mikefairbank** [comment]
Which c file and line number is this routine at  approximately?  I could take a look and see if I can suggest what to do here.

**Comment by soruk42** [comment]
The error is triggered in array.c line 594, but the actual calculation will be in evaluate.c, probably function fmmul() starting line 2899.

**Comment by mikefairbank** [comment]
Ok thanks, will try now...

**Comment by mikefairbank** [comment]
Have fixed this and created a pull request for it.

**Comment by soruk42** [comment]
Thank you - just merged it. Looks good (and thank you for taking care of the integer version too!)

**Comment by mikefairbank** [comment]
Ok, great!  Glad to help - your project has helped me resurrect my old basic programs.  Thank you.
