### ISSUE TITLE
Plot triangle clipping bug

### ISSUE THREAD

**Issue by mikefairbank** [stardot/MatrixBrandy#84]
When I run this code, the triangle should be entirely off the top of the screen (i.e. not drawn at all), but the code leaves the top-most line of pixels on the screen coloured white.  Hence I believe there is a clipping bug.

10MODE 9
20MOVE-15.6,1290.12:MOVE170.41,1169.88:PLOT85,-25.85,1369.835

**Comment by soruk42** [comment]
My starting Y coordinate for limiting range was 0, should have been -1.

**Comment by mikefairbank** [comment]
I've checked that and it seems to be working well now.  Fix is good.  Thank you.
