### ISSUE TITLE
macos fails to build

### ISSUE THREAD

**Issue by JTurco32** [stardot/MatrixBrandy#85]
hello,

i am getting the error building the latest MaxrixBrandy. i have installed the SDL1.2 package mentioned.

```ld: library not found for -lrt```

**Comment by soruk42** [comment]
Did you build using
`make -f build/makefile.macosx` ?

**Comment by soruk42** [comment]
Please do a git pull, I've found other (unrelated) issues with MacOS X building and fixed them.

**Comment by JTurco32** [comment]
That worked. many thanks!
