### ISSUE TITLE
Plot 13 mode 73 bug?

### ISSUE THREAD

**Issue by mikefairbank** [stardot/MatrixBrandy#86]
The following code misses out a pixel in the right-hand polyline, but I don't think it should do. The left one doesn't miss it out. Also, why is the left polyline straight?
10MODE73
20VDU29,1606;1286;
30GCOL3,15
40MOVE -565,269:PLOT 13,-566,289:PLOT 13,-565,300
50MOVE 565,-269:PLOT 13,566,-289:PLOT 13,565,-300

Note that plot 13 draws a line but misses out the end point. So the consecutive plot statements should not xor any overlapping point out of existence. But this does seem to be happening on the right hand line.

**Comment by soruk42** [comment]
Should be fixed by commit 6abc6849a8d2ad017016eea6eba55a8274e9b864.  It is not dependent on which screen mode, after email communication was able to replicate on MODE 19 as well thus able to compare with RISC OS.

**Comment by mikefairbank** [comment]
Yes, I've tested this and it works.  Thank you!  Please consider adding the logical screen sizes to https://github.com/stardot/MatrixBrandy/blob/master/docs/ScreenModes.txt as the logical screen size of mode 70 (i.e. 2048 by 1152, corresponding to a physical screen size of 1024 by 576) surprised me.
