### ISSUE TITLE
How many colours in mode 73?

### ISSUE THREAD

**Issue by mikefairbank** [stardot/MatrixBrandy#87]
How many colours should mode 73 have? The document https://github.com/stardot/MatrixBrandy/blob/master/docs/ScreenModes.txt says 4, but it seems there are many more.

**Comment by soruk42** [comment]
That document was WAY out of date, thank you for highlighting it. I've updated it and pushed it to the repo, but the definitive source is in src/scrcommon.h. Also, modes 64 and up are redefinable so you can make it whatever you want it to be.

**Comment by mikefairbank** [comment]
Thank you!  BTW, how do these high-res modes work?  If I do mode 75, and then fill the screen with carriage returns, then it doesn't allow me to type in the bottom 10 rows or so of the window.  So is there a "text window" defined?  Then if I do MOVE0,0:DRAW 1360*4,384*12, it draws a line from the bottom left of the screen.  Then I press a few more carriage returns, and it scrolls the whole screen up - not just the text window portion of the screen.  Is it meant to work like that?

**Comment by soruk42** [comment]
Nope, not supposed to work like that. My brain definitely hit a bad sector when I was entering those mode details, as 384/8 is 48 not 36!  I've pushed a fix for this, and have kicked off a rebuild of the Windows nightlies.

**Comment by mikefairbank** [comment]
Super!  Thanks.
