### ISSUE TITLE
strlcpy on RISC OS

### ISSUE THREAD

**Issue by brad0** [stardot/MatrixBrandy#93]
Is there a macro or some means of determining the RISC OS version?

I noticed 5.30 did a whole sync of a bunch of stuff from FreeBSD which meant
bringing in strlcpy  and strlcat.

https://www.riscosopen.org/content/downloads/summary-rom-5-30/tungsten-5-30

**Comment by soruk42** [comment]
RISC OS is an awkward one - I build using a cross compiler with the UnixLib module as a dependency (supplied with the cross compiler). So, until strlcpy and friends are included in the cross compiler's libc headers and abstraction library, Matrix Brandy will have to continue using the internal my_strlcpy() and the macro that implements strlcat() using strncat+strlen.

**Comment by brad0** [comment]
Ok, cool. Wasn't sure about RISC OS just thought I would mention what I noticed.

**Comment by soruk42** [comment]
Closing this as it depends on a toolchain update which rarely sees updates...
