### ISSUE TITLE
Problem importing basic programs from b-em with line endings &0d

### ISSUE THREAD

**Issue by mikefairbank** [stardot/MatrixBrandy#94]
I've had a problem importing a program from a .ssd file from a bbc micro into a textfile for brandy.

I loaded the basic program from the ssd file into b-em, and on b-em, i chose the menu item "Print to file".  Then in b-em, I did VDU2.  LIST.  VDU3.  Then I opened the file saved in linux.

I found the line-end characters were &0d.  It would not load into brandy like this.  When I hand-wrote the same program in my linux text editor, it set the line end characters to hex &0a.  And brandy could load this file.  (Have I got that the right way around?)  Anyway, in the text editor on linux, both file formats would load and display correctly.  But in brandy, only one of them would be imported correctly and parsed.  Is that correct?

Anyway the file that Brandy cannot parse (with the &0d line endings) is attached.
[TEMP.txt](https://github.com/user-attachments/files/17201907/TEMP.txt)

I'm on the version of brandy which comes with ubuntu 24.01 in the repositories, git commit 1bc77f8.

**Comment by soruk42** [comment]
Part of the tools that come with the dos2unix package is mac2unix (as the &0D line ending is also that of the classic MacOS). Just run that on the text files then Brandy will be fine with it.  Of course, unix2mac does the reverse if you want to take a Brandy program over to Acorn kit.

Also, Matrix Brandy can read (but not write) Acorn (and Russell) tokenised files, so there is actually no need to convert, just extract the file from the .ssd image and LOAD it straight into Brandy.

**Comment by mikefairbank** [comment]
Thanks, that worked.  Would it be worth making brandy more tolerant to both kinds of line endings, if the linux text editors are that tolerant?

**Comment by soruk42** [comment]
Not as easy as it sounds, under the lid the textfile reading uses fgets() which reads a line of text into a buffer, terminated with &0A (or EOF). But I'll look into it.

**Comment by mikefairbank** [comment]
Ok well it's not critical.  Your workaround has sorted my need out.  But I did find it confusing that the linux text editor was displaying the file fine, and brandy couldn't parse it.  It wasn't until I decided to hexdump it that I found out there was a subtle difference in there.  (It could be considered to be the linux text editor's fault for _hiding_ this relatively-major difference in file endings?)

**Comment by soruk42** [comment]
Fair point.  And, you should consider just trying to load the tokenised file as-is into Brandy, now if _that_ doesn't work you've definitely hit a bug!

**Comment by soruk42** [comment]
Brandy can't open a .ssd file, but you can extract a tokenised BASIC program from it and load that, in the same way you extracted the text file from the .ssd and attempted to load that.

**Comment by soruk42** [comment]
Having found an easy-to-read implementation of fgets(), I've written a version (multifgets) that can handle the multiple line ending formats so CR, CR/LF and LF are all cleanly handled, and repointed the appropriate calls to it. Your TEMP.txt now loads cleanly.

**Comment by mikefairbank** [comment]
Ok, great.  Thanks.  And thank you for the tip of accessing the VDFS file system within b-em.  That will be useful.

**Comment by soruk42** [comment]
Closing - fixed by commit 181305d
