### ISSUE TITLE
1.23.4 distfile naming is different from the rest

### ISSUE THREAD

**Issue by brad0** [stardot/MatrixBrandy#95]
I noticed for the 1.23.4 the distfile naming is different than all of the previous releases.

https://brandy.matrixnetwork.co.uk/releases/

https://brandy.matrixnetwork.co.uk/releases/MatrixBrandy-1.23.3.tar.xz
https://brandy.matrixnetwork.co.uk/releases/MatrixBrandy.1.23.4.tar.xz

Seems kind of odd.

**Comment by soruk42** [comment]
Good spot, typo on my end of course (and as such the link on the web page was broken).

I've copied it to the correct name.

Many thanks,
-- Michael

On 10 November 2024 10:29:50 GMT, Brad Smith ***@***.***> wrote:
>I noticed for the 1.23.4 the distfile naming is different than all of the previous releases.
>
>https://brandy.matrixnetwork.co.uk/releases/
>
>https://brandy.matrixnetwork.co.uk/releases/MatrixBrandy-1.23.3.tar.xz
>https://brandy.matrixnetwork.co.uk/releases/MatrixBrandy.1.23.4.tar.xz
>
>Seems kind of odd.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/stardot/MatrixBrandy/issues/95
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from a lethargic brick, please excuse my brevity.
